# Header
menu:
  Home: /
  Archives: /archives
  About: /About
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  HEXO: http://hexo.io
  热前端: http://reqianduan.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:
baidu_tongji: true

# Duoshuo
duoshuo_shortname: IO10

# Baidu share
baidushare: true