# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "favicon.ico"
    high_res_favicon: "/icons/favicon.png"
    apple_touch_icon: "/icons/favicon.png"
    keywords:

# Jump Links Settings
url:
    rss: "/atom.xml"
    daily_pic: "#"
    logo: "/"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
#scheme: Nexus
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "简约 是复杂的最终形式"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true
    pjax: false

# Reading experience
reading:
    entry_excerpt: 80
    #code_highlight: atom-one-dark

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5"
    #bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/img/myavatar.jpg"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    random_thumbnail: "/img/random/material-"
    footer_image:
        #upyun_logo:
            #link: "https://www.upyun.com/"
            #src: "/img/upyun_logo.png"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# Card Elevation Level
card_elevation: 2


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: pangjian1010@gmail.com
    twitter:
    facebook:
    googleplus: "https://www.google.com/"
    weibo: "http://weibo.com/siriuspj"
    instagram:
    tumblr:
    github: "https://github.com/pangjian"
    linkedin: "https://www.linkedin.com/in/健-庞-44777310b"
    zhihu:
    bilibili:
    telegram:

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: true
    qq: true
    telegram: false

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto:pangjian1010@gamil.com"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: false
        icon: chrome_reader_mode
        divider: true
    pages:
        关于我:
            link: "/About"
            icon: person
            divider: false
        标签云:
            link: "/tags"
            icon: 'cloud circle'
            divider: false
        友情链接:
            link: "/links"
            icon: link
            divider: false
    article_num:
        use: false
        divider: false
    footer:
        divider: true
        theme: true
        support: false
        feedback: false
        material: false

# Qrcode for redirect at other device
qrcode: true

# Support Pin posts on the top of the list
topPost: false

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.
materialcdn:
    use:
    base:

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: changyan
    shortname: IO10
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "/js/embed.js"
    changyan_appid: cysXHT0S8
    changyan_conf: prod_7175b98e3f97497da9c5ab94e3fb73fb
    changyan_thread_key_type: path
# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key: -dFQ3V3gswysE7f5VTM_

# Analytics Systems
analytics:
    baidu_id:
    google_id:

# Leancloud Views
leancloud:
    enable: true
    app_id: BvJcby3BNlDWQWq9qjji2NEK-gzGzoHsz
    app_key: 3IcnGJ5Ad8PCCzUe2vLuDIaz
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
